#
server.port=18080
#
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/pensieve
spring.datasource.username=prpvdata
spring.datasource.password=paic1234
