#
server.port=18080
#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/testdb
spring.datasource.username=test
spring.datasource.password=test
